// <auto-generated />
namespace OpcUa.Client.Core.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EndpointEntityAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EndpointEntityAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201804010144102_EndpointEntityAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
